name: incloud

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'
    
      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Setup Dependencies
        run: sudo apt-get install libpcap-dev 
           
      - name: Install Python dependencies
        run: pip install -r https://github.com/maurosoria/dirsearch/blob/master/requirements.txt

      - name: Cache Go
        id: cache-go
        uses: actions/cache@v3
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setting up ProjectDiscovery tools
        env:
          GO111MODULE: on
        run: |
          go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install -v github.com/projectdiscovery/dnsx/cmd/dnsx@latest
          go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
          go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
          go install -v github.com/projectdiscovery/mapcidr/cmd/mapcidr@latest
          git clone https://github.com/maurosoria/dirsearch.git --depth 1
        shell: bash


      - name: Running SubFinder for passive DNS enumeration
        run: |
          rm -f ~/.config/subfinder/provider-config.yaml 2>/dev/null || true
          subfinder -dL input/domains.txt --config config/subfinder-config.yaml -o output/passive_subdomains.txt
        shell: bash

      - name: Running dnsx for valid DNS filtering 
        run: |
          dnsx -l output/passive_subdomains.txt -t 50 | tee output/active_subdomains.txt
        shell: bash

      - name: Running naabu to check top 1000 ports
        run: |
          naabu -list output/active_subdomains.txt  -rate 10000 -top-ports 1000 | tee output/active_ports.txt
        shell: bash


      - name: Running httpx for HTTP webservers probbing
        run: |
          httpx -l output/active_ports.txt -title
          httpx -l output/active_ports.txt | tee output/active_urls.txt
        shell: bash
      - name: Running dirscan 
        run: |
          while read url; do
              python3 dirsearch/dirsearch.py -u "$url" -e php,html,js,json \
                --plain-text-report=output/dirsearch_$(echo $url | sed 's/[^a-zA-Z0-9]/_/g').txt
          done < output/active_urls.txt
          cat output/dirsearch_*.txt > output/dirsearch_results.txt
          tar -czvf output/dirsearch_results.tar.gz output/dirsearch_results.txt
        shell: bash
      

      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add output/active_ports.txt
          git add output/active_urls.txt
          git add output/dirout.tar.csv
      - name: Commit results to Github
        run: |
          git config --local user.email "hacker_8171@qq.com"
          git config --global user.name "PLA007"
          git commit -m "InCloud Report" -a --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
